
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const HANDLE_POSTS_LIKE = 'HANDLE_POSTS_LIKE';
export const HANDLE_COMMENTS_LIKE = 'HANDLE_COMMENTS_LIKE';
export const HANDLE_ADD_COMMENT = 'HANDLE_ADD_COMMENT';
export const HANDLE_ADD_COMMENT_SUCCESS = 'HANDLE_ADD_COMMENT_SUCCESS';

